.TH SCENE 5 "28 MARCH 2020" "Version 1.0" "scene manpage"
.SH NAME
scene - the scene configuration file for minirt
.SH DESCRIPTION
the input file for 
.B minirt.
It represents the configuration of the scene simulated by minirt. 
.br
It should contain
.B one
and only
.B one 
of these entities : 
.B RESOLUTION,
.B AMBIENT LIGHT.
Furthermore, at least one
.B CAMERA
should be configured. Otherwise an error is to be expected.
.PP
Each line must respect the folowing rules :
.br
- One and only one entity may be declared per line.
.br
- a line represent the configuration of no more than one entity.
.br
- entities may be seperated by 0 or more empty lines.
the syntax of each entity configuration is detailed in the syntax section.

.SH SYNTAX

.SH \tRESOLUTION
.TP
.B ID
R
.TP
.B Width
an integer representing the width of the window. It should be bigger than 0. otherwise, an error is reported.
.TP
.B Height
an integer represnting the height of the window. Like the width, the program reports an error when the height is less than 1.

.SH \tAMBIENT LIGHT
.TP
.B ID
A
.TP
.B Ratio
a real number representing the ratio of the ambient light. It must in the range between 0 and 1.
.TP
.B RGB
an rgb format color : R,G,B. Each of these components should be a positive integer, and should not exceed 255.

.SH \tCAMERA
.TP
.B ID
c
.TP
.B Position
a 3 dimensional coordinates : x,y,z. 
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B FOV
the horizontal field of view of the camera in degrees. It has to be in the range [0,180].

.SH \tLIGHT
.TP
.B ID
l
.TP
.B Position
a 3 dimensional coordinates : x,y,z.
.TP
.B Brightness
the brightness ratio of the light. It should be in the range [0,1].
.TP
.B RGB
an rgb format color : R,G,B. Each of these components should be a positive integer, and should not exceed
255.

.SH \tSPHERE
.TP
.B ID
sp
.TP
.B Position
the 3 dimensional coordinates of the sphere center.
.TP
.B Diameter
the diameter of the sphere. Naturally it should be a positive real number.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tPLANE
.TP
.B ID
pl
.TP
.B Position
the 3 dimensional coordinates of the sphere center.
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tSQUARE
.TP
.B ID
sq
.TP
.B Position
the 3 dimensional coordinates of the sphere center.
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Side size
it should be a positive real number.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tCYLINDER
.TP
.B ID
cy
.TP
.B Position
the 3 dimensional coordinates of the center of one of the cylinder caps.
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Diameter
it should be a positive real number.
.TP
.B Height
a positive real number representing the distance between the cylinder caps'centers.
.TP
.B Caps
it accepts two values : 1 representing caps on; 0 representing caps off.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tTRIANGLE
.TP
.B ID
tr
.TP
.B P1
the 3 dimensional coordinates of the first point of the triangle.
.TP
.B P2
the 3 dimensional coordinates of the second point of the triangle.
.TP
.B P3
the 3 dimensional coordinates of the third point of the triangle.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tCONE
.TP
.B ID
co
.TP
.B Vertex
the 3 dimensional coordinates of the cone vertex.
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Height
it should be a positive real number.
.TP
.B Angle
it should be between 0 and 180.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tCUBE
.TP
.B ID
cu
.TP
.B Position
the 3 dimensional coordinates of the cube position (its center).
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Side size
it should be a positive real number.
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tPYRAMID
.TP
.B ID
py
.TP
.B Position
the 3 dimensional coordinates of the pyramid position (the center of its base).
.TP
.B Orientation
a 3 dimensional vector : x,y,z. Each of these components must be in range [-1,1].
.TP
.B Side size
it should be a positive real number.
.TP
.B Apex
the 3 dimensional coordinates of the pyramid apex.
.TP
.TP
.B Texture
refer to
.I texture(6)
for more information.

.SH \tSKYBOX
.TP
.B ID
SK
.TP
.B Right
the texture (image) of the right side of the skybox.
.TP
.B Left
the texture (image) of the left side of the skybox.
.TP
.B Top
the texture (image) of the top of the skybox.
.TP
.B Bottom
the texture (image) of the bottom of the skybox.
.TP
.B Front
the texture (image) of the front of the skybox.
.TP
.B Back
the texture (image) of the back of the skybox.

.SH \tANTI-ALIASING
.TP
.B ID
AA
.TP
.B Factor
an integer between 1 and 10. If it exceeds 10, it will be set to 10. If it is less than 1, an error will occur. If this entity is not declared, a factor of 1 will be used.

.SH \tSEPIA
.TP
.B ID
SE
.TP
.B Option
1 if sepia is on, and 0 if sepia filter is off. In case this entity is not declared, the sepia filter is set to 0.

